# Generated by Django 2.1.11 on 2020-06-14 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indv_name', models.CharField(max_length=200)),
                ('indv_place', models.CharField(max_length=200)),
                ('indv_internet_bandwidth', models.CharField(max_length=200)),
                ('indv_satifactory', models.CharField(max_length=200)),
                ('indv_started_using_vct_name', models.DateTimeField(verbose_name='date published')),
                ('indv_recommend_vct', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200)),
                ('org_place', models.CharField(max_length=200)),
                ('org_internet_bandwidth', models.CharField(max_length=200)),
                ('org_satifactory', models.CharField(max_length=200)),
                ('org_started_using_vct_name', models.DateTimeField(verbose_name='date published')),
                ('org_recommend_vct', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prob_occur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probl_occur_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='org_problem_occurred',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Prob_occur'),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_used_vct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.VCT'),
        ),
        migrations.AddField(
            model_name='individual',
            name='indv_problem_occurred',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Prob_occur'),
        ),
        migrations.AddField(
            model_name='individual',
            name='indv_used_vct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.VCT'),
        ),
    ]
