# Generated by Django 2.1.11 on 2020-06-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200614_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='indv_started_using_vct_name',
            field=models.DateField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_started_using_vct_name',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
