# Generated by Django 2.1.11 on 2020-06-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200614_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vct',
            name='vct_active_users',
            field=models.IntegerField(default=0),
        ),
    ]
