# Generated by Django 2.1.11 on 2020-06-18 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200618_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respondance_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='respondance',
            name='res_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Respondance_type'),
        ),
    ]
